receivers:
  zipkin:
  otlp:
    protocols:
      grpc:
  tcplog:
    listen_address: "0.0.0.0:54525"
exporters:
  logging:
  zipkin:
    endpoint: "http://zipkin-all-in-one:9411/api/v2/spans"
processors:
  batch:
extensions:
  health_check:
  zpages:
    endpoint: :55679
service:
  extensions: [zpages, health_check]
  pipelines:
    traces:
      receivers: [zipkin]
      processors: [batch]
      exporters: [zipkin]
      #metrics:
      #receivers: [otlp]
      #processors: [batch]
      #exporters: [debug]
    logs:
      receivers: [tcplog]
      processors: [batch]
      exporters: [logging]
